name: example

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  class_fields_annotation:
    path: ../../class_fields_annotation

dev_dependencies:
  build_runner: ^2.1.7
  class_fields:
    path: ../
